import { Readable } from 'stream';
import { config } from 'dotenv';
import wretch from 'wretch';
import { createStreamFromFile, jsonStreamify } from '../src/index';

// Load environment variables from .env file
config();

// Validate and extract required environment variables
function getRequiredEnvVar(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `Missing required environment variable: ${name}. ` +
        'Please set it in your .env file or environment. ' +
        'See .env.example for configuration template.'
    );
  }
  return value;
}

// SparkPost API configuration
const SPARKPOST_API_KEY = getRequiredEnvVar('SPARKPOST_API_KEY');
const SPARKPOST_BASE_URL = process.env.SPARKPOST_BASE_URL || 'https://api.sparkpost.com/api/v1';
const SPARKPOST_API_URL = `${SPARKPOST_BASE_URL}/transmissions`;

// Email configuration from environment
const TEST_EMAIL = getRequiredEnvVar('TEST_EMAIL');
const FROM_EMAIL = getRequiredEnvVar('FROM_EMAIL');
const FROM_NAME = getRequiredEnvVar('FROM_NAME');

interface SparkPostAttachment {
  name: string;
  type: string;
  data: string | Readable; // Base64 encoded content or stream (before conversion)
}

interface SparkPostTransmission {
  options: {
    sandbox: boolean;
  };
  content: {
    from: {
      name: string;
      email: string;
    };
    subject: string;
    html: string;
    text?: string;
    attachments?: SparkPostAttachment[];
  };
  recipients: Array<{
    address: {
      name?: string;
      email: string;
    };
  }>;
}

function createSampleAttachments() {
  console.log('📎 Sample attachment files are already available in examples/ directory\n');
}

async function sendEmailWithAttachments() {
  console.log('📧 Preparing SparkPost email with attachments...\n');

  createSampleAttachments();

  // Create the transmission payload with file streams
  const transmission = {
    options: {
      sandbox: false, // Use sandbox mode for testing
    },
    content: {
      from: {
        name: FROM_NAME,
        email: FROM_EMAIL,
      },
      subject: 'Email with Attachments via json-streamify',
      html: `
        <html>
          <body>
            <h2>json-streamify Email Demo</h2>
            <p>This email was sent using the SparkPost Transmissions API with attachments that were automatically converted from file streams to Base64 encoding.</p>
            
            <h3>Included Attachments:</h3>
            <ul>
              <li><strong>sample-document.pdf</strong> - A sample PDF document</li>
              <li><strong>sample-data.csv</strong> - Sample CSV data</li>
              <li><strong>generated-report.txt</strong> - A sample text report</li>
            </ul>
            
            <p>The json-streamify library automatically handled the Base64 encoding of all file streams, making it easy to include binary attachments in JSON API requests.</p>
            
            <hr>
            <p><small>Generated by json-streamify example</small></p>
          </body>
        </html>
      `,
      text: `json-streamify Email Demo

This email was sent using the SparkPost Transmissions API with attachments that were automatically converted from file streams to Base64 encoding.

Included Attachments:
- sample-document.pdf: A sample PDF document  
- sample-data.csv: Sample CSV data
- generated-report.txt: A sample text report

The json-streamify library automatically handled the Base64 encoding of all file streams.

Generated by json-streamify example`,
      attachments: [
        {
          name: 'sample-document.pdf',
          type: 'application/pdf',
          data: createStreamFromFile('examples/sample-document.pdf'),
        },
        {
          name: 'sample-data.csv',
          type: 'text/csv',
          data: createStreamFromFile('examples/sample-data.csv'),
        },
        {
          name: 'generated-report.txt',
          type: 'text/plain',
          data: createStreamFromFile('examples/generated-report.txt'),
        },
      ],
    },
    recipients: [
      {
        address: {
          name: 'Test Recipient',
          email: TEST_EMAIL,
        },
      },
    ],
  } satisfies SparkPostTransmission;

  console.log('🔄 Converting transmission data with json-streamify...');

  // Use json-streamify to convert the transmission object
  // File streams in attachments[].data will be automatically converted to Base64
  const jsonStream = jsonStreamify(transmission, null, 2);

  console.log('📊 Transmission statistics:');
  console.log(`   Number of attachments: ${transmission.content.attachments?.length || 0}`);

  // Show estimated file sizes before conversion
  console.log('\n🔍 Attachment file sizes:');
  transmission.content.attachments?.forEach((attachment, index) => {
    console.log(`   ${index + 1}. ${attachment.name}`);
    console.log(`      Type: ${attachment.type}`);
    console.log(
      `      Source: ${attachment.data instanceof Readable ? 'Readable stream' : 'Unknown'}`
    );
  });

  console.log('\n🌐 Sending request to SparkPost API...');

  try {
    const result = await wretch(SPARKPOST_API_URL)
      .headers({
        Authorization: SPARKPOST_API_KEY,
        'Content-Type': 'application/json',
      })
      .body(jsonStream)
      .options({ duplex: 'half' })
      .post()
      .json<{
        results: {
          total_rejected_recipients: number;
          total_accepted_recipients: number;
          id: string;
        };
      }>();

    console.log('✅ Email sent successfully!');
    console.log('📋 SparkPost response:');
    console.log(`   Transmission ID: ${result.results.id}`);
    console.log(`   Accepted recipients: ${result.results.total_accepted_recipients}`);
    console.log(`   Rejected recipients: ${result.results.total_rejected_recipients}`);
  } catch (error) {
    console.error('❌ Email send failed:', error);
    throw error;
  }
}

async function main() {
  try {
    console.log('🚀 json-streamify SparkPost Email Demo\n');

    await sendEmailWithAttachments();

    console.log('\n🎉 Demo completed successfully!');
    console.log('   - File streams were automatically converted to Base64');
    console.log('   - Email with attachments was prepared for SparkPost API');
    console.log('   - All file handling was done in-memory with streams');

    console.log('\n✅ Demo completed - sample files remain in examples/ directory');
  } catch (error) {
    console.error('❌ Demo failed:', error);

    if (error instanceof Error && error.message.includes('Missing required environment variable')) {
      console.log('\n💡 Configuration help:');
      console.log('   1. Copy .env.example to .env: cp .env.example .env');
      console.log('   2. Edit .env with your configuration:');
      console.log('      - SPARKPOST_API_KEY: Get from https://app.sparkpost.com/account/api-keys');
      console.log('      - TEST_EMAIL: Email address to send test to');
      console.log('      - FROM_EMAIL: Your verified sending domain email');
      console.log('      - FROM_NAME: Display name for sender');
    }

    process.exit(1);
  }
}

void main();
